const paragraphs = [
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",

"chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh","chiraghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
  "The sun dipped low behind the hills, casting golden light across the valley. Birds chirped their final songs of the day. A gentle breeze rustled the leaves. Everything seemed to pause in quiet harmony.",
  "The city never truly slept, lights flickering like stars below. Cars moved like rivers of metal and light. People hurried past, lost in their own worlds. Somewhere, music spilled from a street performer’s violin.",
  "In the library's silence, time felt slower. Dust danced in the rays of sunlight through high windows. She turned each page with care, savoring the words. Books whispered stories older than her own.",
  "Rain tapped softly on the rooftop, a steady rhythm in the quiet night. Thunder rumbled in the distance. Inside, warmth and lamplight offered comfort. She curled up with a cup of tea and a worn novel.",
  "He stood at the edge of the dock, watching the water ripple. The lake was still except for the occasional fish. Memories drifted in like the mist. This was where everything had changed.",
  "Morning light filtered through the curtains, gentle and golden. A kettle whistled from the kitchen. The dog stretched and yawned beside the bed. It was the start of another peaceful day.",
  "Autumn leaves crunched under their boots as they walked. The air smelled of smoke and earth. Trees stood like flames frozen in time. They didn’t speak, but the silence felt full.",
  "She stared at the map, tracing paths with her finger. So many places she hadn’t seen yet. The thought made her heart ache with longing. One day, she promised herself.",
  "The garden buzzed with life in the morning sun. Bees moved from bloom to bloom with purpose. A cat watched lazily from the porch. Everything felt alive and content.",
  "The ocean stretched endlessly ahead, silver under the moonlight. Waves kissed the shore again and again. He felt small, but not alone. The stars blinked down with ancient wisdom.",
  "A single candle flickered in the dark room. Shadows danced on the stone walls. The air smelled of wax and parchment. She read aloud, her voice steady and calm.",
  "They huddled beneath the umbrella, laughing as rain soaked their shoes. The storm didn’t matter anymore. His hand found hers in the cold. It was enough to be there, together.",
  "Snow blanketed the ground in silence. Each step crunched like a whisper. Breath clouded in the air before fading. Winter had arrived with quiet majesty.",
  "She ran through the tall grass, breathless with joy. Laughter echoed behind her like music. The sky was wide and open above. Nothing else mattered in that moment.",
  "The old clock ticked steadily in the hallway. Its sound marked the slow passing of the night. Pictures on the wall watched in still silence. Time moved on, unnoticed.",
  "He typed furiously, chasing thoughts before they vanished. Ideas sparked and flowed like water. Words filled the screen in a rush. For once, inspiration was kind.",
  "She lit the lantern, its glow soft against the darkness. Outside, wolves howled at the moon. Inside, she wrapped the blanket tighter. Stories would keep her safe tonight.",
  "Children’s laughter filled the playground like music. Swings creaked, slides clattered, and voices rang out. Joy was everywhere, unfiltered and real. For them, the world was still full of magic.",
  "The campsite glowed with firelight and warmth. Marshmallows hissed and melted over flames. They shared stories between sips of cocoa. The forest listened in peaceful silence.",
  "A paper plane soared across the classroom. It landed softly near her desk. She smiled and unfolded the message. Sometimes, friendship began with folded wings.",
  "The painter stepped back, studying her canvas. Colors danced across the scene with energy. It wasn’t perfect, but it was hers. That made it beautiful.",
  "He walked the quiet hallway, echoes following each step. Lockers stood like sentinels in the gloom. Something about empty schools felt haunted. Memories clung to the walls.",
  "She opened the music box, and the melody began. Notes floated like memories through the air. Tears welled in her eyes, unbidden. It had been her mother’s favorite tune.",
  "The train rumbled across the tracks, steady and strong. Fields blurred past the window like dreams. He watched, lost in thought and miles. The journey mattered more than the arrival.",
  "They stood atop the mountain, wind rushing around them. The view stole their breath more than the climb. Below, the world looked small and quiet. Up here, everything felt possible."
];
